import streamlit as st
import os
import io
# import psycopg  # psycopg v3 main package (migrated from psycopg2)
from psycopg_pool import ConnectionPool  # Lightweight, thread-safe pooling (best practice Nov 2025)
import minio
import getpass
import polars as pl
import requests
import atexit
import framework.utils as framework_utils
import framework.analysis_framework as analysis_framework
import framework.snowflake_connections as snowflake_connections
import framework.snowflake_orchestrator as snowflake_orchestrator
from concurrent.futures import ThreadPoolExecutor, as_completed
import mimetypes
import gzip
import tempfile


ST_KEY_PREFIX_STARTUP = "startup.py__"


#### 1. DATABASE FUNCTIONALITY ####################################################################


DB_URL_GROUP = os.getenv('DB_URL_GROUP')
DB_URL_APP = os.getenv('DB_URL_APP')  # Aren't actually using this yet, but it would be used to get the archive compatibility IDs so we only display archives that are compatible with the currently running image.
DB_URL_COMMON = os.getenv('DB_URL_COMMON')
DB_URL_DATA_MANAGER = os.getenv('DB_URL_DATA_MANAGER')
APP_SHORTNAME = os.getenv('APP_SHORTNAME')


@st.cache_resource()
def get_connection_pool(db_url: str):
    """Return a psycopg v3 ConnectionPool for a given Postgres conninfo.

    Notes (Nov 2025 best practice):
    - psycopg_pool.ConnectionPool offers automatic recycling and safe usage from multiple threads.
    - Use pool.connection() context manager for automatic return and rollback on exceptions.
    - Explicit close() registered at exit for clean shutdown.
    - We keep min_size=1/max_size=10 similar to previous configuration; tune as needed.
    """
    if framework_utils.platform() != "local":
        return None  # Snowflake path does not use PostgreSQL.
    try:
        pool = ConnectionPool(
            conninfo=db_url,
            min_size=1,
            max_size=10,
            timeout=30,      # seconds to wait for a free connection (adjust if needed)
            num_workers=3,   # async maintenance workers; small number for lightweight local usage
        )
        atexit.register(lambda: pool.close())
        return pool
    except Exception as e:
        st.error(f"Failed to create database pool: {e}")
        return None


# Create four tables for the app. Note it should be largely consistent with what's in 01_set_up_non_user_objects.sql for now, and later on we should probably have this function, if even still necessary, just run setup.sql so we don't have to maintain this logic in two places.
def set_up_postgresql():
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_COMMON).connection() as conn_common:
                with conn_common.cursor() as cur:
                    # Create schema if it doesn't exist
                    cur.execute(f"""
                        CREATE SCHEMA IF NOT EXISTS admin_schema
                    """)
                    
                    # Check if user_groups_table table exists and is empty
                    cur.execute(f"""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables
                            WHERE table_schema = 'admin_schema'
                            AND table_name = 'user_groups_table'
                        )
                    """)
                    table_exists = cur.fetchone()[0]
                    # Create user_groups_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS admin_schema.user_groups_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            username VARCHAR(255) UNIQUE NOT NULL,
                            user_group VARCHAR(255),
                            user_added_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            who_added VARCHAR(255),
                            user_email VARCHAR(255)
                        )
                    """)
                    # Only insert initial users if table was just created (didn't exist before)
                    if not table_exists:
                        initial_users = [
                            ('andrew', 'dmap', 'andrew', 'andrew@example.com'),
                            ('jessica', 'ABC Lab', 'andrew', 'jessica@example.com'),
                            ('Tessa', 'dmap', 'andrew', 'tessa@example.com')
                        ]
                        cur.executemany(
                            """
                            INSERT INTO admin_schema.user_groups_table (username, user_group, who_added, user_email)
                            VALUES (%s, %s, %s, %s)
                            """,
                            initial_users,
                        )

            with get_connection_pool(DB_URL_GROUP).connection() as conn_group:
                with conn_group.cursor() as cur:
                    # Create schema if it doesn't exist
                    cur.execute(f"""
                        CREATE SCHEMA IF NOT EXISTS {APP_SHORTNAME}_schema
                    """)
                    
                    # Create app_sessions_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS {APP_SHORTNAME}_schema.app_sessions_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            app_session_id VARCHAR(255) UNIQUE NOT NULL,
                            username VARCHAR(255),
                            user_group VARCHAR(255),
                            startup_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            explicit_shutdown_time TIMESTAMP,
                            container_image_id VARCHAR(255),
                            compute_resource VARCHAR(255)
                        )
                    """)

                    # Create archives_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS {APP_SHORTNAME}_schema.archives_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            creator VARCHAR(255),
                            user_group VARCHAR(255),
                            archive_description TEXT,
                            current_git_commit VARCHAR(255),
                            container_image_id VARCHAR(255),
                            archive_id VARCHAR(255) UNIQUE NOT NULL,
                            app_session_id VARCHAR(255),
                            archive_compatibility_id VARCHAR(255),
                            creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    """)

                    # Create jobs_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS {APP_SHORTNAME}_schema.jobs_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            job_id VARCHAR(255) UNIQUE NOT NULL,
                            job_name VARCHAR(255),
                            job_status VARCHAR(255),
                            submitter VARCHAR(255),
                            submitter_group VARCHAR(255),
                            app_session_id VARCHAR(255),
                            worker_image_id VARCHAR(255),
                            submission_time TIMESTAMP,
                            start_time TIMESTAMP,
                            completion_time TIMESTAMP,
                            failure_time TIMESTAMP,
                            compute_resource VARCHAR(255)
                        )
                    """)

            with get_connection_pool(DB_URL_APP).connection() as conn_app:
                with conn_app.cursor() as cur:
                    # Create schema if it doesn't exist
                    cur.execute(f"""
                        CREATE SCHEMA IF NOT EXISTS general_schema
                    """)
                    
                    # Check if image_metadata_table table exists and is empty
                    cur.execute(f"""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables
                            WHERE table_schema = 'general_schema'
                            AND table_name = 'image_metadata_table'
                        )
                    """)
                    table_exists = cur.fetchone()[0]
                    # Create image_metadata_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS general_schema.image_metadata_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            image_id VARCHAR(255) UNIQUE NOT NULL,
                            name VARCHAR(255),
                            tag VARCHAR(255),
                            git_commit VARCHAR(255),
                            environment_yaml_file TEXT,
                            archive_compatibility_id VARCHAR(255),
                            image_added_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            who_added VARCHAR(255)
                        )
                    """)

            with get_connection_pool(DB_URL_DATA_MANAGER).connection() as conn_manager:
                with conn_manager.cursor() as cur:
                    # Create schema if it doesn't exist
                    cur.execute(f"""
                        CREATE SCHEMA IF NOT EXISTS general_schema
                    """)
                    
                    # Check if image_metadata_table table exists and is empty
                    cur.execute(f"""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables
                            WHERE table_schema = 'general_schema'
                            AND table_name = 'image_metadata_table'
                        )
                    """)
                    table_exists = cur.fetchone()[0]
                    # Create image_metadata_table table.
                    cur.execute(f"""
                        CREATE TABLE IF NOT EXISTS general_schema.image_metadata_table (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            image_id VARCHAR(255) UNIQUE NOT NULL,
                            name VARCHAR(255),
                            tag VARCHAR(255),
                            git_commit VARCHAR(255),
                            environment_yaml_file TEXT,
                            image_added_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            who_added VARCHAR(255)
                        )
                    """)
            return True
        except Exception as e:
            st.error(f"Failed to set up databases: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        pass


def write_archive_database_data(row_tuple):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        INSERT INTO {APP_SHORTNAME}_schema.archives_table (creator, user_group, archive_description, current_git_commit, container_image_id, archive_id, app_session_id, archive_compatibility_id)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    """, row_tuple)
            return True
        except Exception as e:
            st.error(f"Failed to write archive database data: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                INSERT INTO {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.archives_table (creator, user_group, archive_description, current_git_commit, container_image_id, archive_id, app_session_id, archive_compatibility_id)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, row_tuple).collect()
            return True
        except Exception as e:
            st.error(f"Failed to write archive database data: {e}")
            return False


def log_app_session(row_tuple):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        INSERT INTO {APP_SHORTNAME}_schema.app_sessions_table (app_session_id, username, user_group, container_image_id)
                        VALUES (%s, %s, %s, %s)
                    """, row_tuple)
            return True
        except Exception as e:
            st.error(f"Failed to log app session: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                INSERT INTO {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.app_sessions_table (app_session_id, username, user_group, container_image_id)
                VALUES (?, ?, ?, ?)
            """, row_tuple).collect()
            return True
        except Exception as e:
            st.error(f"Failed to log app session: {e}")
            return False


def set_app_session_shutdown_time(app_session_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        UPDATE {APP_SHORTNAME}_schema.app_sessions_table
                        SET explicit_shutdown_time = %s
                        WHERE app_session_id = %s
                    """, (framework_utils.get_timestamp(), app_session_id))
            return True
        except Exception as e:
            st.error(f"Failed to set app session shutdown time: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                UPDATE {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.app_sessions_table
                SET explicit_shutdown_time = CURRENT_TIMESTAMP()
                WHERE app_session_id = ?
            """, (app_session_id,)).collect()
            return True
        except Exception as e:
            st.error(f"Failed to set app session shutdown time: {e}")
            return False


@st.cache_data()
def get_user_group(username):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_COMMON).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT user_group
                        FROM admin_schema.user_groups_table
                        WHERE username = %s
                    """, (username,))
                    user_group = cur.fetchone()
            return user_group[0] if user_group else None
        except Exception as e:
            st.error(f"Failed to retrieve user group: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            result = session.sql(f"""
                SELECT user_group
                FROM common_db.admin_schema.user_groups_table
                WHERE username = ?
            """, (username,)).collect()
            return result[0]["USER_GROUP"] if result else None
        except Exception as e:
            st.error(f"Failed to retrieve user group: {e}")
            return None


@st.cache_data()
def get_user_groups_table_data():
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_COMMON).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT username, user_group, user_added_time, who_added, user_email
                        FROM admin_schema.user_groups_table
                    """)
                    rows = cur.fetchall()
            df = pl.DataFrame(rows, schema=["username", "user_group", "user_added_time", "who_added", "user_email"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve user groups table data: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            rows = session.sql(f"""
                SELECT username, user_group, user_added_time, who_added, user_email
                FROM common_db.admin_schema.user_groups_table
            """).collect()
            df = pl.DataFrame(rows, schema=["username", "user_group", "user_added_time", "who_added", "user_email"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve user groups table data: {e}")
            return None


@st.cache_data()
def get_app_sessions_table_data():
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT app_session_id, username, user_group, startup_time, explicit_shutdown_time, container_image_id, compute_resource
                        FROM {APP_SHORTNAME}_schema.app_sessions_table
                        ORDER BY startup_time DESC
                    """)
                    rows = cur.fetchall()
            df = pl.DataFrame(rows, schema=["app_session_id", "username", "user_group", "startup_time", "explicit_shutdown_time", "container_image_id", "compute_resource"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve app sessions table data: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            rows = session.sql(f"""
                SELECT app_session_id, username, user_group, startup_time, explicit_shutdown_time, container_image_id, compute_resource
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.app_sessions_table
                ORDER BY startup_time DESC
            """).collect()
            df = pl.DataFrame(rows, schema=["app_session_id", "username", "user_group", "startup_time", "explicit_shutdown_time", "container_image_id", "compute_resource"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve app sessions table data: {e}")
            return None


@st.cache_data()
def get_archives_table_data():
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT creator, user_group, archive_description, current_git_commit, container_image_id, archive_id, app_session_id, creation_time, archive_compatibility_id
                        FROM {APP_SHORTNAME}_schema.archives_table
                        ORDER BY creation_time DESC
                    """)
                    rows = cur.fetchall()
            df = pl.DataFrame(rows, schema=["creator", "user_group", "archive_description", "current_git_commit", "container_image_id", "archive_id", "app_session_id", "creation_time", "archive_compatibility_id"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve archives_table table data: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            rows = session.sql(f"""
                SELECT creator, user_group, archive_description, current_git_commit, container_image_id, archive_id, app_session_id, creation_time, archive_compatibility_id
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.archives_table
                ORDER BY creation_time DESC
            """).collect()
            df = pl.DataFrame(rows, schema=["creator", "user_group", "archive_description", "current_git_commit", "container_image_id", "archive_id", "app_session_id", "creation_time", "archive_compatibility_id"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve archives_table table data: {e}")
            return None


@st.cache_data()
def get_jobs_table_data():
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    columns = "job_id, job_name, job_status, submitter, submitter_group, app_session_id, worker_image_id, submission_time, start_time, completion_time, failure_time, compute_resource"
                    cur.execute(f"""
                        SELECT {columns}
                        FROM {APP_SHORTNAME}_schema.jobs_table
                        ORDER BY submission_time DESC NULLS LAST
                    """)
                    rows = cur.fetchall()
            df = pl.DataFrame(rows, schema=["job_id", "job_name", "job_status", "submitter", "submitter_group", "app_session_id", "worker_image_id", "submission_time", "start_time", "completion_time", "failure_time", "compute_resource"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve jobs_table table data: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            columns = "job_id, job_name, job_status, submitter, submitter_group, app_session_id, worker_image_id, submission_time, start_time, completion_time, failure_time, compute_resource"
            rows = session.sql(f"""
                SELECT {columns}
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                ORDER BY submission_time DESC NULLS LAST
            """).collect()
            df = pl.DataFrame(rows, schema=["job_id", "job_name", "job_status", "submitter", "submitter_group", "app_session_id", "worker_image_id", "submission_time", "start_time", "completion_time", "failure_time", "compute_resource"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve jobs_table table data: {e}")
            return None


@st.cache_data()
def get_available_archives(archive_compatibility_id: str):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT creator, creation_time, archive_description, archive_id, app_session_id
                        FROM {APP_SHORTNAME}_schema.archives_table
                        WHERE archive_compatibility_id = %s
                        ORDER BY creation_time DESC
                    """, (archive_compatibility_id,))
                    rows = cur.fetchall()
            df = pl.DataFrame(rows, schema=["Creator", "Creation time", "Archive description", "Archive ID", "App session ID"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve available archives_table: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            rows = session.sql(f"""
                SELECT creator, creation_time, archive_description, archive_id, app_session_id
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.archives_table
                WHERE archive_compatibility_id = ?
                ORDER BY creation_time DESC
            """, (archive_compatibility_id,)).collect()
            df = pl.DataFrame(rows, schema=["Creator", "Creation time", "Archive description", "Archive ID", "App session ID"], strict=False, orient="row")
            return df
        except Exception as e:
            st.error(f"Failed to retrieve available archives_table: {e}")
            return None


def log_job(row_tuple):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        INSERT INTO {APP_SHORTNAME}_schema.jobs_table (job_id, job_name, submitter, submitter_group, app_session_id)
                        VALUES (%s, %s, %s, %s, %s)
                    """, row_tuple)
            return True
        except Exception as e:
            st.error(f"Failed to log job: {e}. It's possible that job with ID {row_tuple[0]} already exists (unique constraint violated), which would indicate a job ID generation bug.")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                INSERT INTO {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table (job_id, job_name, submitter, submitter_group, app_session_id)
                VALUES (?, ?, ?, ?, ?)
            """, row_tuple).collect()
            return True
        except Exception as e:
            st.error(f"Failed to log job: {e}. It's possible that job with ID {row_tuple[0]} already exists (unique constraint violated), which would indicate a job ID generation bug.")
            return False


def update_job_status(job_id, new_status, time_column):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        UPDATE {APP_SHORTNAME}_schema.jobs_table
                        SET job_status = %s, {time_column} = %s
                        WHERE job_id = %s
                    """, (new_status, framework_utils.get_timestamp(), job_id))
            return True
        except Exception as e:
            st.error(f"Failed to update status of job {job_id} to {new_status} and update {time_column}: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                UPDATE {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                SET job_status = ?, {time_column} = CURRENT_TIMESTAMP()
                WHERE job_id = ?
            """, (new_status, job_id)).collect()
            return True
        except Exception as e:
            st.error(f"Failed to update status of job {job_id} to {new_status} and update {time_column}: {e}")
            return False


def log_compute_resource_for_job(job_id: str, compute_resource: str):
    if framework_utils.platform() == "local":
        pass
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                UPDATE {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                SET compute_resource = ?
                WHERE job_id = ?
            """, (compute_resource, job_id)).collect()
            return True
        except Exception as e:
            st.error(f"Failed to set compute resource for job {job_id} to {compute_resource}: {e}")
            return False


def get_job_status(job_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT job_status
                        FROM {APP_SHORTNAME}_schema.jobs_table
                        WHERE job_id = %s
                    """, (job_id,))
                    job_status = cur.fetchone()
            return job_status[0] if job_status else None
        except Exception as e:
            st.error(f"Failed to retrieve status of job {job_id}: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            result = session.sql(f"""
                SELECT job_status
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                WHERE job_id = ?
            """, (job_id,)).collect()
            return result[0]["JOB_STATUS"] if result else None
        except Exception as e:
            st.error(f"Failed to retrieve status of job {job_id}: {e}")
            return None


@st.cache_data()
def get_job_function_name(job_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT job_name
                        FROM {APP_SHORTNAME}_schema.jobs_table
                        WHERE job_id = %s
                    """, (job_id,))
                    job_name = cur.fetchone()
            return job_name[0] if job_name else None
        except Exception as e:
            st.error(f"Failed to retrieve function name of job {job_id}: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            result = session.sql(f"""
                SELECT job_name
                FROM {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                WHERE job_id = ?
            """, (job_id,)).collect()
            return result[0]["JOB_NAME"] if result else None
        except Exception as e:
            st.error(f"Failed to retrieve function name of job {job_id}: {e}")
            return None


def set_worker_image_id(job_id, worker_image_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        UPDATE {APP_SHORTNAME}_schema.jobs_table
                        SET worker_image_id = %s
                        WHERE job_id = %s
                    """, (worker_image_id, job_id))
            return True
        except Exception as e:
            st.error(f"Failed to set worker image ID for job {job_id} to {worker_image_id}: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                UPDATE {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.jobs_table
                SET worker_image_id = ?
                WHERE job_id = ?
            """, (worker_image_id, job_id)).collect()
            return True
        except Exception as e:
            st.error(f"Failed to set worker image ID for job {job_id} to {worker_image_id}: {e}")
            return False


def record_explicit_shutdown_time(app_session_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_GROUP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        UPDATE {APP_SHORTNAME}_schema.app_sessions_table
                        SET explicit_shutdown_time = %s
                        WHERE app_session_id = %s
                    """, (framework_utils.get_timestamp(), app_session_id))
            return True
        except Exception as e:
            st.error(f"Failed to record explicit shutdown time for app session {app_session_id}: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            session.sql(f"""
                UPDATE {get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema.app_sessions_table
                SET explicit_shutdown_time = CURRENT_TIMESTAMP()
                WHERE app_session_id = ?
            """, (app_session_id,)).collect()
            return True
        except Exception as e:
            st.error(f"Failed to record explicit shutdown time for app session {app_session_id}: {e}")
            return False


#### 2. OBJECT STORAGE FUNCTIONALITY ##############################################################


MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT')
MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY')
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY')
ARCHIVES_BUCKET_NAME = os.getenv('ARCHIVES_BUCKET_NAME')
OLD_ARCHIVES_BUCKET_NAME = os.getenv('OLD_ARCHIVES_BUCKET_NAME')
JOB_INPUTS_BUCKET_NAME = os.getenv('JOB_INPUTS_BUCKET_NAME')
JOB_OUTPUTS_BUCKET_NAME = os.getenv('JOB_OUTPUTS_BUCKET_NAME')
DATA_OBJECTS_BUCKET_NAME = os.getenv('DATA_OBJECTS_BUCKET_NAME')


@st.cache_resource()
def get_object_storage_client():
    if framework_utils.platform() == "local":
        try:
            return minio.Minio(
                MINIO_ENDPOINT,
                access_key=MINIO_ACCESS_KEY,
                secret_key=MINIO_SECRET_KEY,
                secure=False  # Set to True for HTTPS
            )
        except Exception as e:
            st.error(f"Failed to create MinIO client: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        pass


@st.cache_data()
def set_up_minio():
    if framework_utils.platform() == "local":
        try:
            client = get_object_storage_client()
            if not client.bucket_exists(ARCHIVES_BUCKET_NAME):
                client.make_bucket(ARCHIVES_BUCKET_NAME)
            if not client.bucket_exists(JOB_INPUTS_BUCKET_NAME):
                client.make_bucket(JOB_INPUTS_BUCKET_NAME)
            if not client.bucket_exists(JOB_OUTPUTS_BUCKET_NAME):
                client.make_bucket(JOB_OUTPUTS_BUCKET_NAME)
            if not client.bucket_exists(DATA_OBJECTS_BUCKET_NAME):
                client.make_bucket(DATA_OBJECTS_BUCKET_NAME)
            if not client.bucket_exists(OLD_ARCHIVES_BUCKET_NAME):
                client.make_bucket(OLD_ARCHIVES_BUCKET_NAME)
            return True
        except Exception as e:
            st.error(f"Failed to set up object storage: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        pass


def upload_zip_object_data(bucket_name, zip_name, zip_buffer, db_schema: str = None):
    if framework_utils.platform() == "local":
        try:
            client = get_object_storage_client()

            # Get the size of the zip buffer
            zip_buffer.seek(0, io.SEEK_END)
            zip_size = zip_buffer.tell()
            zip_buffer.seek(0)

            client.put_object(
                bucket_name=bucket_name,
                object_name=f"{zip_name}.zip",
                data=zip_buffer,
                length=zip_size,
                content_type='application/zip'
            )
            return True
        except Exception as e:
            st.error(f"Failed to write {zip_name}.zip to bucket {bucket_name}: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            zip_buffer.seek(0)
            if db_schema is None:
                db_schema = f"{get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema"
            results = session.file.put_stream(
                input_stream=zip_buffer,
                stage_location=f"@{db_schema}.{bucket_name}_stage/{zip_name}.zip",
                auto_compress=False,
            )
            return results
        except Exception as e:
            st.error(f"Failed to write {zip_name}.zip to bucket {bucket_name}: {e}")
            return None


# This could potentially be a lot of data, so we don't want to cache it using st.cache_data().
def download_zip_object_data(bucket_name, zip_name, db_schema: str = None):
    if framework_utils.platform() == "local":
        response = None
        try:
            client = get_object_storage_client()
            object_name = f"{zip_name}.zip"
            response = client.get_object(bucket_name, object_name)
            # NOTE: For very large objects consider streaming in chunks instead of reading all at once.
            data = response.read()
            response.close()
            return io.BytesIO(data)
        except Exception as e:
            st.error(f"Failed to download object data: {e}")
            if response:
                response.close()
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            if db_schema is None:
                db_schema = f"{get_user_group(get_current_username())}_group_db.{APP_SHORTNAME}_schema"
            stage_path = f"@{db_schema}.{bucket_name}_stage/{zip_name}.zip"
            bytes_io = session.file.get_stream(stage_location=stage_path)
            bytes_io.seek(0)
            return bytes_io
        except Exception as e:
            st.error(f"Failed to download {zip_name}.zip from bucket {bucket_name}: {e}")
            return None
        

def list_objects_in_bucket(bucket_name: str, db_schema: str = None):
    if framework_utils.platform() == "local":
        try:
            client = get_object_storage_client()
            objects = client.list_objects(bucket_name)
            object_list = [obj.object_name for obj in objects]
            return object_list
        except Exception as e:
            st.error(f"Failed to list objects in {bucket_name} bucket: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            if db_schema is None:
                user_group = get_user_group(get_current_username())
                db_schema = f"{user_group}_group_db.curated_schema"
            stage_location = f"@{db_schema}.{bucket_name}_stage"
            files = session.file.list(stage_location=stage_location)
            object_list = [file.name.removeprefix(f"{bucket_name}_stage/") for file in files]
            return object_list
        except Exception as e:
            st.error(f"Failed to list objects in {bucket_name} stage in database.schema {db_schema}: {e}")
            return None


def download_objects_parallel(
    bucket_name: str,
    object_names: list[str],
    dest_dir: str,
    db_schema: str | None = None,
    max_workers: int | None = None,
    chunk_size: int = 1024 * 1024,
    gunzip_if_gz: bool = True,
):
    """Download objects in parallel for the active platform (local MinIO or Snowflake stage).

    Mirrors upload_objects_parallel design (shared core + per-platform adapters) for symmetry & less duplication.

    Features:
        - Parallel streaming download (chunk_size per read).
        - Optional transparent gunzip: if remote object ends in .gz and gunzip_if_gz=True, writes decompressed file locally (drops .gz) then removes original .gz.
        - Memory efficiency: streamed read/write & streamed gunzip (chunk_size blocks, no full-file buffering).
        - Simplified: no retries, backoff, checksum/etag verification, or local skip-existing (downloads overwrite).

    Return: {final_local_name: {status:'ok'|'error', path:local_path|None, size:int|None, error:Exception|None}}
    """
    os.makedirs(dest_dir, exist_ok=True)
    platform_value = framework_utils.platform()
    effective_workers = max_workers or (os.cpu_count() or 1)

    def _gunzip_if_needed(local_path: str) -> tuple[str, int]:
        """If gunzip enabled and file endswith .gz, stream decompress (chunk_size blocks) to path without .gz; remove original .gz; return (final_path, size)."""
        if not gunzip_if_gz or not local_path.lower().endswith('.gz'):
            return local_path, os.path.getsize(local_path) if os.path.exists(local_path) else None
        final_path = local_path[:-3]
        try:
            with gzip.open(local_path, 'rb') as src, open(final_path, 'wb') as dst:
                for chunk in iter(lambda: src.read(chunk_size), b''):
                    if not chunk:
                        break
                    dst.write(chunk)
            try: os.remove(local_path)
            except Exception: pass
            return final_path, os.path.getsize(final_path)
        except Exception:
            # Decompression failed; keep original .gz
            return local_path, os.path.getsize(local_path) if os.path.exists(local_path) else None

    def _core_parallel_download(get_stream_func):
        """Shared parallel engine: obtains stream via adapter, writes file, optional gunzip, returns result dict entries."""
        def _download_one(obj_name: str):
            stream = None
            local_path = os.path.join(dest_dir, obj_name)
            parent = os.path.dirname(local_path)
            if parent:
                os.makedirs(parent, exist_ok=True)
            try:
                stream = get_stream_func(obj_name)
                with open(local_path, 'wb') as f:
                    for chunk in iter(lambda: stream.read(chunk_size), b''):
                        if not chunk:
                            break
                        f.write(chunk)
                try:
                    stream.close()
                except Exception:
                    pass
                final_path, size = _gunzip_if_needed(local_path)
                return obj_name, {'status': 'ok', 'path': final_path, 'size': size, 'final_name': os.path.basename(final_path)}
            except Exception as e:
                if stream:
                    try: stream.close()
                    except Exception: pass
                return obj_name, {'status': 'error', 'error': e, 'path': None, 'size': None}

        results: dict[str, dict] = {}
        with ThreadPoolExecutor(max_workers=effective_workers) as executor:
            future_map = {executor.submit(_download_one, name): name for name in object_names}
            for fut in as_completed(future_map):
                original_name = future_map[fut]
                try:
                    obj_name, res = fut.result()
                    results[obj_name] = res
                except Exception as e:
                    results[original_name] = {'status': 'error', 'error': e, 'path': None, 'size': None}
        failures = [(k, v) for k, v in results.items() if v['status'] != 'ok']
        if failures:
            st.warning(f"{len(failures)} downloads did not complete for the stated reasons (might be fine!)")
            st.write(failures)
        else:
            st.success(f"Downloaded {len(results)} objects.")
        return results

    if platform_value == "local":
        try:
            client = get_object_storage_client()
            if client is None:
                st.error("MinIO client unavailable.")
                return None
            def _get_stream(name: str):
                return client.get_object(bucket_name, name)
            return _core_parallel_download(_get_stream)
        except Exception as e:
            st.error(f"Failed to download objects from MinIO bucket: {e}")
            return None
    elif platform_value == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            if db_schema is None:
                st.error("db_schema must be provided for Snowflake downloads.")
                return None
            stage_prefix = f"@{db_schema}.{bucket_name}_stage"
            def _get_stream(name: str):
                stage_location = f"{stage_prefix}/{name}"
                return session.file.get_stream(stage_location=stage_location)
            return _core_parallel_download(_get_stream)
        except Exception as e:
            st.error(f"Failed to download objects from Snowflake stage: {e}")
            return None


def upload_objects_parallel(
    bucket_name: str,
    file_paths: list,  # Iterable of filesystem path strings and/or Streamlit UploadedFile objects.
    db_schema: str | None = None,
    gzip_if_possible: bool = False,
    overwrite: bool = False,
    max_workers: int | None = None,
    chunk_size: int = 1024 * 1024,
):
    """Upload path strings or Streamlit UploadedFile objects to object storage for the active platform.

        Platform branches (explicit):
            local      -> MinIO bucket (put_object).
            snowflake  -> Snowflake stage (file.put_stream).

        Features:
            - Optional gzip (adds .gz) for inputs not already .zip/.gz (streams in chunk_size blocks).
            - Optional overwrite prevention (skip if object already exists).
            - Memory efficiency: path compression streams in 1MB chunks; UploadedFile also streamed (no full duplicate buffer).
            - Snowflake overwrite uses native put_stream overwrite flag when overwrite=True (avoids pre-listing).

        Return: {object_name: {status: 'ok'|'skipped-existing'|'error', size: int|None, error: Exception|None}}.

        Extensibility: Add a new platform by adding another top-level elif branch that defines two callables:
                exists(name)->bool and upload(name,size,stream,content_type)->None then calls _core_parallel(...).
        """

    def _is_uploaded_file(item):
        """Return True if item looks like a Streamlit UploadedFile (has .read() and .name)."""
        return hasattr(item, "read") and hasattr(item, "name")

    def _compute_object_name(item):
        """Return basename for a path or original .name for an UploadedFile (collision possible if duplicate basenames)."""
        if isinstance(item, str):
            return os.path.basename(item)
        if _is_uploaded_file(item):
            return item.name
        raise TypeError("Items must be str paths or Streamlit UploadedFile objects.")

    def _prepare_item(item):
        """Return (size_bytes, stream, inferred_mime_type, file_handle_or_None) for a path or UploadedFile (always infers type)."""
        if isinstance(item, str):
            size = os.path.getsize(item)
            f = open(item, "rb")
            content_type = mimetypes.guess_type(item)[0] or "application/octet-stream"
            return size, f, content_type, f
        # UploadedFile case.
        bytes_data = item.read()
        size = len(bytes_data)
        data_stream = io.BytesIO(bytes_data)
        content_type = getattr(item, "type", None) or mimetypes.guess_type(item.name)[0] or "application/octet-stream"
        item.seek(0)
        return size, data_stream, content_type, None

    # Determine worker count: explicit override or CPU heuristic.
    effective_workers = max_workers or (os.cpu_count() or 1)

    def _core_parallel_upload(exists_func, upload_func):
        """Execute uploads with provided existence and upload callables; handles gzip and overwrite semantics."""
        def _upload_one(item):
            # Determine final object name first (gzip adds .gz); perform existence check on final name before any heavy work.
            original_name = _compute_object_name(item)
            lower = original_name.lower()
            will_gzip = gzip_if_possible and not (lower.endswith('.zip') or lower.endswith('.gz'))
            final_name = original_name + '.gz' if will_gzip else original_name
            f = None
            temp_path_to_remove = None
            size = None
            data_stream = None
            content_type = None
            try:
                # Early skip based on final name only (raw existence does not block creating gzip variant).
                if not overwrite and exists_func(final_name):
                    return final_name, {'status': 'skipped-existing', 'size': None}

                if will_gzip:
                    # Stream compression to temp file without loading entire file into memory.
                    source_stream = None
                    if isinstance(item, str):
                        source_stream = open(item, 'rb')
                    elif _is_uploaded_file(item):
                        # Read in 1MB chunks directly from UploadedFile object.
                        item.seek(0)
                        source_stream = item
                    else:
                        raise TypeError("Items must be str paths or Streamlit UploadedFile objects.")
                    with tempfile.NamedTemporaryFile(delete=False) as tmp_out:
                        temp_path_to_remove = tmp_out.name
                        with gzip.GzipFile(fileobj=tmp_out, mode='wb') as gz_out:
                            for chunk in iter(lambda: source_stream.read(chunk_size), b''):
                                if not chunk:
                                    break
                                gz_out.write(chunk)
                    # Close source_stream if it's a file handle (path case).
                    if isinstance(item, str) and source_stream:
                        try: source_stream.close()
                        except Exception: pass
                    # Open compressed for upload.
                    f = open(temp_path_to_remove, 'rb')
                    data_stream = f
                    size = os.path.getsize(temp_path_to_remove)
                    content_type = 'application/gzip'
                else:
                    # Non-gzip path: prepare item normally (this may read UploadedFile fully into memory).
                    size, data_stream, content_type, f = _prepare_item(item)

                upload_func(final_name, size, data_stream, content_type)
                return final_name, {'status': 'ok', 'size': size}
            except Exception as e:
                return final_name, {'status': 'error', 'error': e}
            finally:
                if f:
                    try: f.close()
                    except Exception: pass
                if temp_path_to_remove:
                    try: os.remove(temp_path_to_remove)
                    except Exception: pass

        # Parallel execution.
        results: dict[str, dict] = {}
        with ThreadPoolExecutor(max_workers=effective_workers) as executor:
            future_map = {executor.submit(_upload_one, item): item for item in file_paths}
            for fut in as_completed(future_map):
                item = future_map[fut]
                try:
                    obj_name, res = fut.result()
                    results[obj_name] = res
                except Exception as e:
                    fallback_name = _compute_object_name(item)
                    results[fallback_name] = {'status': 'error', 'error': e}
        failures = [(k, v) for k, v in results.items() if v['status'] != 'ok']
        if failures:
            st.warning(f"{len(failures)} uploads did not complete for the stated reasons (might be fine!)")
            st.write(failures)
        else:
            st.success(f"Uploaded {len(results)} objects.")
        return results

    platform_value = framework_utils.platform()
    if platform_value == "local":
        try:
            client = get_object_storage_client()
            if client is None:
                st.error("MinIO client unavailable.")
                return None
            def _exists_local(name: str) -> bool:
                try:
                    client.stat_object(bucket_name, name)
                    return True
                except Exception:
                    return False
            def _upload_local(name: str, size: int, stream, content_type: str):
                client.put_object(bucket_name=bucket_name, object_name=name, data=stream, length=size, content_type=content_type)
            return _core_parallel_upload(_exists_local, _upload_local)
        except Exception as e:
            st.error(f"Failed to upload objects to MinIO: {e}")
            return None
    elif platform_value == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            if db_schema is None:
                st.error("db_schema must be provided for Snowflake uploads.")
                return None
            stage_prefix = f"@{db_schema}.{bucket_name}_stage"
            def _exists_snowflake(name: str) -> bool:
                # Only perform existence check when overwrite is False; otherwise skip for performance.
                if overwrite:
                    return False
                try:
                    listing = session.file.list(stage_location=f"{stage_prefix}/{name}")
                    return any(entry.get('name') == name for entry in listing)
                except Exception:
                    return False
            def _upload_snowflake(name: str, size: int, stream, content_type: str):
                # size/content_type are ignored by Snowflake put_stream; overwrite handled natively.
                session.file.put_stream(
                    input_stream=stream,
                    stage_location=f"{stage_prefix}/{name}",
                    auto_compress=False,
                    overwrite=overwrite
                )
            return _core_parallel_upload(_exists_snowflake, _upload_snowflake)
        except Exception as e:
            st.error(f"Failed to upload objects to Snowflake stage: {e}")
            return None


def delete_objects(bucket_name: str, object_names: list[str], db_schema: str | None = None):
    results = {}
    if framework_utils.platform() == "local":
        try:
            client = get_object_storage_client()
            for name in object_names:
                try:
                    client.remove_object(bucket_name, name)
                    results[name] = "ok"
                except Exception as e:
                    results[name] = f"error: {e}"
            if any(v.startswith("error") for v in results.values()):
                st.warning(f"Some deletions failed in bucket {bucket_name}: {results}")
                return False
            return True
        except Exception as e:
            st.error(f"Failed bulk delete in bucket {bucket_name}: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        if db_schema is None:
            st.error("db_schema required for Snowflake delete.")
            return False
        try:
            session = snowflake_connections.get_snowpark_session()
            for name in object_names:
                try:
                    stage_location = f"@{db_schema}.{bucket_name}_stage/{name}"
                    session.file.remove(stage_location=stage_location)
                    results[name] = "ok"
                except Exception as e:
                    results[name] = f"error: {e}"
            if any(v.startswith("error") for v in results.values()):
                st.warning(f"Some deletions failed in stage {db_schema}.{bucket_name}_stage: {results}")
                return False
            return True
        except Exception as e:
            st.error(f"Failed bulk delete in stage {db_schema}: {e}")
            return False
        
@st.cache_data()
# From the image_metadata_table, get the archive_compatibility_id for a given container_image_id.
def get_archive_compatibility_id(container_image_id):
    if framework_utils.platform() == "local":
        try:
            with get_connection_pool(DB_URL_APP).connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(f"""
                        SELECT archive_compatibility_id
                        FROM general_schema.image_metadata_table
                        WHERE image_id = %s
                    """, (container_image_id,))
                    result = cur.fetchone()
            return result[0] if result else None
        except Exception as e:
            st.error(f"Failed to retrieve archive compatibility ID for image {container_image_id}: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            result = session.sql(f"""
                SELECT archive_compatibility_id
                FROM mawa_app_db.general_schema.image_metadata_table
                WHERE image_id = ?
            """, (container_image_id,)).collect()
            return result[0]["ARCHIVE_COMPATIBILITY_ID"] if result else None
        except Exception as e:
            st.error(f"Failed to retrieve archive compatibility ID for image {container_image_id}: {e}")
            return None


#### 3. ORCHESTRATION FUNCTIONALITY ###############################################################


@st.cache_data()
def get_frontend_image_id():
    if framework_utils.platform() == "local":
        try:
            resp = requests.get("http://docker_orchestrator:8080/frontend_id", timeout=3)
            resp.raise_for_status()
            data = resp.json()
            return data.get("frontend_image_id")
        except Exception as e:
            st.error(f"Could not retrieve frontend image id: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            return snowflake_orchestrator.frontend_id(username=get_current_username(), session=session, app_shortname=os.getenv("APP_SHORTNAME", "app_a"), group_name=get_user_group(get_current_username()), compute_resource=os.getenv("COMPUTE_RESOURCE", "<COMPUTE RESOURCE NOT SET IN ENV>"))
        except Exception as e:
            st.error(f"Could not retrieve frontend image id: {e}")
            return None


def submit_job(job_id, blocking=True, selected_compute_resource: str = None):
    if framework_utils.platform() == "local":
        try:
            update_job_status(job_id, "Submitted", "submission_time")
            if blocking:
                analysis_framework.run_local_analysis(job_id)  # This is the worker code.
            else:  # Asynchronous analysis that should execute analysis_framework.run_local_analysis(job_id) on a worker.
                # Submit to Docker orchestrator, which launches an ephemeral worker container
                resp = requests.post("http://docker_orchestrator:8080/jobs", json={"job_id": job_id}, timeout=10)
                resp.raise_for_status()
                data = resp.json()
                worker_image_id = data.get("worker_image_id")
                # Record the image used by the worker container for traceability
                if worker_image_id:
                    set_worker_image_id(job_id, worker_image_id)
            return True
        except Exception as e:
            st.error(f"Failed to submit job: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            update_job_status(job_id, "Submitted", "submission_time")
            if blocking:
                log_compute_resource_for_job(job_id, f"Sync: {os.getenv('COMPUTE_RESOURCE', '<COMPUTE RESOURCE NOT SET IN ENV>')}")
                analysis_framework.run_local_analysis(job_id)  # This is the worker code.
            else:
                session = snowflake_connections.get_snowpark_session()
                log_compute_resource_for_job(job_id, f"Async: {selected_compute_resource}")
                worker_image_id = snowflake_orchestrator.submit_job(job_id=job_id, username=get_current_username(), session=session, selected_compute_resource=selected_compute_resource, group_name=get_user_group(get_current_username()), app_shortname=os.getenv("APP_SHORTNAME", "app_a"), image_name=os.getenv("IMAGE_NAME", "frontend"), image_tag=os.getenv("IMAGE_TAG", "latest"), app_title=os.getenv("APP_TITLE", "App A"))

                print("Worker image ID returned from Snowflake orchestrator:", worker_image_id, flush=True)

                if worker_image_id:
                    set_worker_image_id(job_id, worker_image_id)
            return True
        except Exception as e:
            st.error(f"Failed to submit job: {e}")
            return False


def shut_down_app():
    if framework_utils.platform() == "local":
        try:
            resp = requests.post("http://docker_orchestrator:8080/shutdown", timeout=10)
            resp.raise_for_status()
            st.success("Application is shutting down...")
            return True
        except Exception as e:
            st.error(f"Failed to shut down app: {e}")
            return False
    elif framework_utils.platform() == "snowflake":
        try:
            session = snowflake_connections.get_snowpark_session()
            snowflake_orchestrator.shutdown(username=get_current_username(), session=session, app_shortname=os.getenv("APP_SHORTNAME", "app_a"), group_name=get_user_group(get_current_username()), compute_resource=os.getenv("COMPUTE_RESOURCE", "<COMPUTE RESOURCE NOT SET IN ENV>"))
            st.success("Application is shutting down...")
            return True
        except Exception as e:
            st.error(f"Failed to shut down app: {e}")
            return False


#### 4. OTHER FUNCTIONALITY #######################################################################


@st.cache_data()
def get_current_username():
    if framework_utils.platform() == "local":
        try:
            try:
                return os.getlogin()
            except (FileNotFoundError, OSError):
                pass
            username = os.getenv('APP_USER') or os.getenv('USER') or os.getenv('USERNAME') or os.getenv('LOGNAME')  # Delete "os.getenv('APP_USER') or " (and modify docker-compose.yml) in the future when we implement running the container as non-root.
            if username:
                return username
            return getpass.getuser()
        except Exception as e:
            st.error(f"Failed to get current username: {e}")
            return None
    elif framework_utils.platform() == "snowflake":
        try:
            return os.getenv("SNOWFLAKE_USER")
        except Exception as e:
            st.error(f"Failed to get current username: {e}")
            return None
