remote_theme: just-the-docs/just-the-docs
title: Multiplex Analysis Web Apps
# logo: "/assets/images/mawa_logo-full.png"  # set a path/url to a logo that will be displayed instead of the title... appears tiny because I think it's expecting an image of text and therefore setting the height, which I currently can't change per https://stackoverflow.com/questions/59811176/changing-logo-svg-file-on-jekyll-github-reducing-pixel-size-does-not-appear-to because I'm using the theme as a remote
color_scheme: light

# Add this line to include MathJax on every page
includes:
  - mathjax.html

# Aux links for the upper right navigation
aux_links:
  "MAWA on GitHub":
    - "https://github.com/ncats/multiplex-analysis-web-apps"
