channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - compilers=1.11.0
  - python=3.9.20
  - streamlit=1.51.0
  - psycopg2=2.9.10
  - pyyaml=6.0.2
  - dill=0.4.0
  - git  # had to remove the version of this to resolve micromamba dependency issues
  - requests=2.32.3
  - minio=7.2.16
  - polars=1.27.1
  - snowflake-snowpark-python=1.39.1
  - matplotlib=3.9.4
  - natsort=8.4.0
  - numpy=2.0.2
  - palantir-sdk=0.12.0
  - pandas=2.2.3
  - plotly=6.0.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - scikit-image=0.24.0
  - scikit-learn=1.6.1
  - anaconda::streamlit-extras=0.6.0
  - tqdm=4.67.1
  - umap-learn=0.5.7
  - pympler=1.1
  - objsize=0.7.1
  - bioconda::phenograph=1.5.7
  - parmap=1.7.0
  - setuptools-scm=8.2.0
  - pynndescent=0.5.13
  - plotnine=0.13.6
  - shapely=2.0.7
  - hnswlib=0.8.0
  - spatialdata=0.2.5
  - dask=2024.8.0
  - pyopenssl=24.2.1
  - numba=0.60.0
  - zarr=2.18.2
  - numcodecs=0.12.1
  - pip=25.0.1
  - pip:
      - st-pages==1.0.1
      - streamlit-javascript==0.1.5
      - parc==0.40
      - sklearn-ann==0.1.2
      - anndata==0.10.9
      - annoy==1.17.3
      - boto3==1.40.45
      - squidpy==1.6.1
      - split-file-reader==0.1.4
