channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.13.9
  - streamlit=1.51.0
  - psycopg=3.2.13
  - psycopg-pool=3.2.8
  - minio=7.2.18
  - polars=1.35.1
  - snowflake-snowpark-python=1.42.0
