channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.12.9
  - streamlit=1.50.0
  - psycopg2=2.9.10  # can probably upgrade to psycopg
  - pyyaml=6.0.2
  - dill=0.3.9
  - git=2.51.0
  - requests=2.32.5
  - minio=7.2.16
  - polars=1.33.0
  - snowflake-snowpark-python=1.38.0
  - pyarrow=18.1.0  # need this due to warning from snowflake-snowpark-python about needing pyarrow < 19.0.0
  - anndata=0.10.9
  - matplotlib=3.10.1
  - natsort=8.4.0
  - numpy=2.1.3
  - palantir-sdk=0.12.0
  - pandas=2.2.3
  - plotly=6.0.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - scikit-image=0.25.2
  - scikit-learn=1.5.2
  - split-file-reader=0.1.4
  - squidpy=1.6.2
  - anaconda::streamlit-extras=0.6.0
  - tqdm=4.67.1
  - umap-learn=0.5.7
  - pympler=1.1
  - objsize=0.7.1
  - bioconda::phenograph=1.5.7
  - parmap=1.7.0
  - setuptools-scm=8.2.0
  - annoy=1.17.3
  - pynndescent=0.5.13
  - plotnine=0.13.6
  - shapely=2.0.7
  - hnswlib=0.8.0
  - pip=25.0.1
  - pip:
      - st-pages==1.0.1
      - streamlit-javascript==0.1.5
      - parc==0.40
      - sklearn-ann==0.1.2
