spec:
  containers:                           # container list
    - name: frontend
      image: {{IMAGE}}
      env:                                # optional
        SNOWFLAKE_USER: {{SNOWFLAKE_USER}}             # must inject manually; Snowflake does not inject
        SNOWFLAKE_WAREHOUSE: {{SNOWFLAKE_WAREHOUSE}}   # must inject manually; Snowflake does not inject
        TZ: America/New_York
        ARCHIVES_BUCKET_NAME: archives
        OLD_ARCHIVES_BUCKET_NAME: oldarchives
        JOB_INPUTS_BUCKET_NAME: inputs
        JOB_OUTPUTS_BUCKET_NAME: outputs
        DATA_OBJECTS_BUCKET_NAME: objects
        APP_PLATFORM: snowflake
        APP_SHORTNAME: {{APP_SHORTNAME}}
        APP_TITLE: {{APP_TITLE}}
        MONITOR_JOBS_REFRESH_INTERVAL_SECONDS: {{MONITOR_JOBS_REFRESH_INTERVAL_SECONDS}}
        COMPUTE_RESOURCE: {{COMPUTE_RESOURCE}}
        ALL_COMPUTE_RESOURCES: {{ALL_COMPUTE_RESOURCES}}
        IMAGE_NAME: {{IMAGE_NAME}}
        IMAGE_TAG: {{IMAGE_TAG}}
      volumeMounts:                       # optional list
        - name: tmp
          mountPath: {{MOUNTPATH}}
      resources:                          # optional
        requests:
          memory: {{MEMORY}}
          cpu: {{CPU}}
        limits:
          memory: {{MEMORY}}
          cpu: {{CPU}}
  endpoints:                             # optional endpoint list
    - name: web
      port: 8501                     # specify this or portRange
      public: true
      protocol: HTTP
  volumes:                               # optional volume list
    - name: tmp
      source: local
serviceRoles:                   # Optional list of service roles
  - name: web_endpoint_service_role
    endpoints:
      - web
