spec:
  containers:                           # container list
    - name: worker
      image: {{IMAGE}}
      command:                            # optional list of strings
        - "/opt/conda/bin/python"
        - "-c"
        - {{PYTHON_COMMAND}}
      env:                                # optional
        SNOWFLAKE_USER: {{SNOWFLAKE_USER}}             # must inject manually; Snowflake does not inject
        SNOWFLAKE_WAREHOUSE: {{SNOWFLAKE_WAREHOUSE}}   # must inject manually; Snowflake does not inject
        TZ: America/New_York
        ARCHIVES_BUCKET_NAME: archives
        OLD_ARCHIVES_BUCKET_NAME: oldarchives
        JOB_INPUTS_BUCKET_NAME: inputs
        JOB_OUTPUTS_BUCKET_NAME: outputs
        DATA_OBJECTS_BUCKET_NAME: objects
        APP_PLATFORM: snowflake
        APP_SHORTNAME: {{APP_SHORTNAME}}
        APP_TITLE: {{APP_TITLE}}
        MONITOR_JOBS_REFRESH_INTERVAL_SECONDS: {{MONITOR_JOBS_REFRESH_INTERVAL_SECONDS}}
        COMPUTE_RESOURCE: {{COMPUTE_RESOURCE}}
      volumeMounts:                       # optional list
        - name: tmp
          mountPath: {{MOUNTPATH}}
      resources:                          # optional
        requests:
          memory: {{MEMORY}}
          cpu: {{CPU}}
        limits:
          memory: {{MEMORY}}
          cpu: {{CPU}}
  volumes:                               # optional volume list
    - name: tmp
      source: local
